name: 'Publish JSR'
description: |
  This workflow serializes the build binary to Base64 and generates a JSON file with meta data about the file.
  The file then gets published to JSR (@serial/cpp-bindings-linux).

on:
  workflow_call:
    inputs:
      publish:
        description: 'Whether to actually publish'
        required: true
        type: boolean

      version:
        description: 'Package version'
        required: true
        type: string

      x86-64-artifact-name:
        description: 'Name of the x86-64 binary artifact'
        required: true
        type: string

      aarch64-artifact-name:
        description: 'Name of the AArch64 binary artifact'
        required: true
        type: string

      ffi-artifact-name:
        description: 'Name of the target-specific FFI metadata artifact'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  publish-jsr:
    name: 'Publish JSR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Deno'
        uses: denoland/setup-deno@v2
        with:
          deno-version: '2.x'
      
      - name: 'Download x86-64 binary'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.x86-64-artifact-name }}
          path: 'artifacts/x86_64'

      - name: 'Download AArch64 binary'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.aarch64-artifact-name }}
          path: 'artifacts/aarch64'

      - name: 'Download FFI metadata'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.ffi-artifact-name }}
          path: 'artifacts/ffi'

      - name: 'Prepare files for JSR'
        run: |
          mkdir -p ./registries/jsr/bin/x86_64
          cp ./artifacts/x86_64/libcpp_bindings_linux.so ./registries/jsr/bin/x86_64/library.so
          cp ./artifacts/ffi/x86_64.ffi.json ./registries/jsr/bin/x86_64/ffi.json
          
          mkdir -p ./registries/jsr/bin/aarch64
          cp ./artifacts/aarch64/libcpp_bindings_linux.so ./registries/jsr/bin/aarch64/library.so
          cp ./artifacts/ffi/aarch64.ffi.json ./registries/jsr/bin/aarch64/ffi.json

          ./registries/jsr/scripts/binary_to_json.sh \
            ./registries/jsr/bin/x86_64/library.so \
            ./registries/jsr/bin/x86_64/library.json \
            x86_64-linux-gnu

          ./registries/jsr/scripts/binary_to_json.sh \
            ./registries/jsr/bin/aarch64/library.so \
            ./registries/jsr/bin/aarch64/library.json \
            aarch64-linux-gnu

          ./registries/jsr/scripts/set_version.sh \
            registries/jsr/jsr.json \
            "${{ inputs.version }}"
      
      - name: 'Publish package to JSR (normal)'
        if: inputs.publish
        working-directory: registries/jsr
        run: |
          deno publish --allow-dirty

      - name: 'Publish package to JSR (dry-run)'
        if: ${{ !inputs.publish }}
        working-directory: registries/jsr
        run: |
          deno publish --allow-dirty --dry-run
